# Generated by Django 5.0.3 on 2024-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_alter_unique_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendlar",
                "db_table": "brands",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="categories/", null=True, blank=True)),
                ("brand", models.ForeignKey(verbose_name="Brend", to="Brand", on_delete=models.CASCADE)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "db_table": "data",
            },
        ),
    ]
