# Generated by Django 5.0.3 on 2024-03-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=300, unique=True, verbose_name="Nomi"),
        ),
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.AlterUniqueTogether(
            name="telegramuser",
            unique_together={("telegram_id", "phone_number")},
        ),
        migrations.AddField(
            model_name="category",
            name="brand",
            field=models.ManyToManyField(to="bot.brand", verbose_name="Brend"),
        ),
    ]
