# Generated by Django 5.0.3 on 2024-03-29 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_product_remove_telegramuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="brand",
            field=models.ManyToManyField(
                help_text="Bir nechta brendlarni tanlash uchun Control yoki Cmd tugmalari bilan tanlang!",
                to="bot.brand",
                verbose_name="Brend",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qo'shimcha ma'lumoti"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/", verbose_name="Rasmi"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=300, unique=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qo'shimcha ma'lumoti"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.FloatField(default=0.0, verbose_name="Chegirma foizi (%)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Narxi",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Soni"),
        ),
    ]
