# Generated by Django 5.0.3 on 2024-03-31 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_product_category_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_categories",
                to="bot.category",
                verbose_name="Tepa kategoriya",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
