# Generated by Django 5.0.3 on 2024-04-03 07:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0012_order_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_processing", "Jarayonda"),
                    ("confirmed", "Tasdiqlangan"),
                    ("success", "Muvaffaqiyatli"),
                    ("canceled", "Bekor qilingan"),
                    ("payment_canceled", "To'lov bekor qilingan"),
                    ("refunded", "Qaytarilgan"),
                ],
                default="in_processing",
                max_length=20,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Misol uchun: Mo'ljal",
                null=True,
                verbose_name="Qo'shimcha",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="latitude",
            field=models.FloatField(verbose_name="Kenglik"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="longitude",
            field=models.FloatField(verbose_name="Uzunlik"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Mijoz buyurtmani olib ketishi kerak bo'lgan filial.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bot.branch",
                verbose_name="Filial",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="To'lgangan"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="To'liq narxi"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bot.telegramuser",
                verbose_name="Mijoz",
            ),
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Narxi"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Soni",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.order",
                        verbose_name="Buyurtma",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.product",
                        verbose_name="Mahsulot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma mahsuloti",
                "verbose_name_plural": "Buyurtma mahsulotlari",
                "db_table": "order_products",
            },
        ),
    ]
