# Generated by Django 5.0.3 on 2024-04-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0014_alter_order_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="bot.category",
                verbose_name="Tepa kategoriya",
            ),
        ),
    ]
