# Generated by Django 5.0.3 on 2024-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0015_alter_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nomi"),
        ),
    ]
