# Generated by Django 5.0.3 on 2024-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0016_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Chat ID (telegram)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chatlar",
                "db_table": "chats",
            },
        ),
    ]
