# Generated by Django 5.0.3 on 2024-04-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0017_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatOrderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.BigIntegerField(verbose_name="Xabar ID (Telegram)"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.chat",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.order",
                        verbose_name="Buyurtma",
                    ),
                ),
            ],
            options={
                "db_table": "chat_order_messages",
            },
        ),
    ]
