# Generated by Django 5.0.3 on 2024-05-11 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0018_chatordermessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
